【OJT課題_自販機システム】UC01「お金を投入する」機能のテストコードを作成しました
W-Nakayama-24/VendingMachine_CUI pull request #7
Opened 2019-11-11 02:14 UTC by W-Nakayama-24

初めに、
投入金額の上限チェックを行う「DepositExcessChecker」クラスと
上限チェックを呼び出し、投入金額を保持する「VendingMachine」クラスの
テストコードを作成しました。

ご確認をお願い致します。
https://github.com/W-Nakayama-24/VendingMachine_CUI/commit/1b7c9b61e2ecf4a6cc53a88b7c691ff6b31acae1

2019-11-11 04:28 UTC, skashiyama requested changes
- HTML出力とかはしてみました?成果物として求められることがあるので生成して、貼っておくといいかと。
- カバレッジはいくつです?
- 今回はいいですが、テストコードを実装より先に書く方がいいでしょう。

2019-11-11 04:28 UTC, skashiyama commented on test/pkg/VendingMachineTest.java
> +        boolean insertResult = vm.insertMoney(1000);
```suggestion
        int inputMoney = 1000;
        boolean insertResult = vm.insertMoney(inputMoney);
```

2019-11-11 04:28 UTC, skashiyama commented on test/pkg/VendingMachineTest.java
> +        assertThat(getterTestResult, is(1000));
```suggestion
        assertThat(getterTestResult, is(inputMoney));
```
投入した金額と同じ、ということをテストしたいなら、変数宣言してコード上で同じものであることを保証した方がいいです。(これぐらいなら間違えないですが、1000000000000000 とかを手打ちした場合、0が少なくても気づかない + テストが実装がバグっていてテストが通っちゃったらまずいので)

2019-11-11 04:28 UTC, skashiyama commented on test/pkg/DepositExcessCheckerTest.java
> +    public void testCheckDepositExcess1() {
ここだけでなく全テストケースにいえますが、テストケースの名前の付け方がちょっと雑です。
何をテストしているのかわかる名前にしましょう

2019-11-11 04:28 UTC, skashiyama commented on test/pkg/DepositExcessCheckerTest.java
> +    // 希望金額が1000円,投入金額が9000円のとき,加算後に上限を超えるのでfalseを返す
上限って9990ですよね?
このテストで、上限が9990 であることを確認できますか?
仮に上限値が間違えて9995で設定しちゃっていても気づけないです

2019-11-11 04:28 UTC, skashiyama commented on test/pkg/VendingMachineTest.java
> +        assertThat(getterTestResult, is(0));
line 13-15 と内容が被ってませんか?

2019-11-11 04:28 UTC, skashiyama commented on test/pkg/DepositExcessCheckerTest.java
> +    // 希望金額が1000円,投入金額が0円のとき,加算後に上限を超えないのでtrueを返す
投入金額が0より大きい数字の時のテストはあったほうがいいのでは?

2019-11-11 04:28 UTC, skashiyama commented on test/pkg/VendingMachineTest.java
> +        boolean insertResult = vm.insertMoney(9999);
Deposit の状態のテストがないです。
false が来たら deposit が変わっていないことを確認すべきでは?

2019-11-11 05:03 UTC, W-Nakayama-24 commented on test/pkg/VendingMachineTest.java
> +        assertThat(getterTestResult, is(0));
"初めに投入金額が0円であることを確認する"という意図で盛り込んでいました。
テストを実行する流れを見直したときに必要ないことが分かったので削除します。

2019-11-11 06:02 UTC, W-Nakayama-24 commented on test/pkg/DepositExcessCheckerTest.java
> +        boolean checkResult = dexchecker.checkDepositExcess(1, 9990);
>このテストで、上限が9990であることを確認できますか?
仮に上限値が間違えて9995で設定しちゃっていても気づけないです

「単体テストなのだから、実在する貨幣に合わせた引数である必要は無い」という点を見落としていました。
上限を1円だけ上回る形になったときにfalseを返すテストに変更し、9990円が上限であることが分かるようにしました。

2019-11-11 06:04 UTC, W-Nakayama-24 commented on test/pkg/VendingMachineTest.java
> +        assertThat(getResultAfter, is(getResultBefore));
>Deposit の状態のテストがないです。
false が来たら deposit が変わっていないことを確認すべきでは?

機能を呼び出す前と後のDepositをそれぞれ変数に代入しておき、同じであることを確かめるテストを追加しました。

2019-11-11 06:05 UTC, W-Nakayama-24 commented on test/pkg/DepositExcessCheckerTest.java
> +    public void testCheckSuccessFromZero() {
>ここだけでなく全テストケースにいえますが、テストケースの名前の付け方がちょっと雑です。
何をテストしているのかわかる名前にしましょう

番号を振って区別しているだけだったテストメソッドを命名し直しました。いかがでしょうか?

2019-11-11 06:07 UTC, iwanam commented on test/pkg/DepositExcessCheckerTest.java
> +        boolean checkResult = dexchecker.checkDepositExcess(1, 9990);
こういうのを境界値チェックといったりしますな。ifで登場した数値は必ずチェックするのが大事。
ロジックは実在貨幣単位ではないので、入力は貨幣だろうという暗黙の了解を持ってしまうと変なバグを埋め込みます。基本的にはそのインタフェースでどんなものが来ても絶対大丈夫という作りにすることが大事です。

前にクラス図のレビューでちょっと話ましたが、intではなく例えばCoinクラスだったなら、その中でとりうる値しか受け取れないとなる可能性もありましたね。

2019-11-11 06:08 UTC, W-Nakayama-24 commented on test/pkg/DepositExcessCheckerTest.java
> +        boolean checkResult = dexchecker.checkDepositExcess(1000, 1000);
>投入金額が0より大きい数字の時のテストはあったほうがいいのでは?

0円から始まって上限を超えないテストと、
9990円から始まって上限を超えるテストの間に追加しました。

2019-11-11 06:13 UTC, W-Nakayama-24 commented
>カバレッジはいくつです?

それぞれのテストクラスで100%になっています。

![vmtest1](https://user-images.githubusercontent.com/54921025/68564970-77840380-0495-11ea-8547-f7c3ad39a3d1.JPG)
![vmtest2](https://user-images.githubusercontent.com/54921025/68564971-77840380-0495-11ea-926e-6317e09cfe26.JPG)

2019-11-11 06:21 UTC, W-Nakayama-24 commented
>HTML出力とかはしてみました?成果物として求められることがあるので生成して、貼っておくといいかと。
恥ずかしながら、このレビューを拝見するまでそのような機能があること自体知りませんでした。。
調べてみます。

>今回はいいですが、テストコードを実装より先に書く方がいいでしょう。
テストファーストの開発を今までに体験したことがなく、検討もしていませんでした。
次回以降に機会があれば、やってみたいです。

2019-11-11 06:41 UTC, skashiyama requested changes

2019-11-11 06:41 UTC, skashiyama commented on test/pkg/DepositExcessCheckerTest.java
> +    public void testCheckSuccessFromZero() {
- `testCheck` という単語が不要ですね。
  - DepositExcessCheckerTest クラスの中にあるので、テストなのは自明です。(check することも自明)

2019-11-11 06:41 UTC, skashiyama commented on test/pkg/DepositExcessCheckerTest.java
> +        boolean checkResult = dexchecker.checkDepositExcess(1, 9990);
これだと上限値が9989 でもエラーになりませんか?

9989で成功するテストが必要でございます

2019-11-11 07:03 UTC, W-Nakayama-24 commented on test/pkg/DepositExcessCheckerTest.java
> +    public void ReachMaxDeposit() {
>これだと上限値が9989 でもエラーになりませんか?
9989で成功するテストが必要でございます

追加しました。境界値を扱う際には気をつけます…

2019-11-11 07:09 UTC, skashiyama requested changes

2019-11-11 07:09 UTC, skashiyama commented on test/pkg/DepositExcessCheckerTest.java
> +    public void SuccessFromZero() {
```suggestion
    public void successFromZero() {
```

2019-11-11 07:09 UTC, skashiyama commented on test/pkg/VendingMachineTest.java
> +        int requestMoney = 9991;
```suggestion
        int requestMoney = 9990 + 1;
```
境界値 + 1 をテストしたい、ということがわかりやすいようにしましょう

2019-11-11 07:09 UTC, skashiyama commented on test/pkg/DepositExcessCheckerTest.java
> +        boolean checkResult = dexchecker.checkDepositExcess(1, 9989);
```suggestion
        boolean checkResult = dexchecker.checkDepositExcess(1, 9990 - 1);
```
境界値 + 1 をテストしたい、ということがわかりやすいようにしましょう

2019-11-12 01:29 UTC, W-Nakayama-24 commented
レビューありがとうございます。

MainクラスとUserInterfaceクラスが残っていますが、

- 今回は標準入出力を多用したCUIである為、自動テストを回すこと/その為のコードを書くことが非機能要件を保証するうえであまり合理的ではない

- 既に作成した結合テスト仕様書でカバーできているテストケースがいくつかある

以上2点の理由からプルリクエストでない形でレビューをお願いすることにしました。

よろしくお願い致します。

2019-11-12 01:37 UTC, W-Nakayama-24 commented
JUnitで自動テストを実施するのはVendingMachineクラスとDepositExcessCheckerクラスの2つに限定します。
テスト結果の報告は、本日中に実施します。

2019-11-12 01:48 UTC, skashiyama approved these changes

2019-11-12 02:26 UTC, iwanam approved these changes

2019-11-12 05:01 UTC, W-Nakayama-24 commented
カバレッジレポートをHTML出力しました。
以下のリンクよりプレビューをご覧いただけます。
https://htmlpreview.github.io/?https://raw.githubusercontent.com/W-Nakayama-24/VendingMachine_CUI/testcode/test/ojt_sandbox/index.html

![creport1](https://user-images.githubusercontent.com/54921025/68643464-d2306480-0554-11ea-86e9-47bb6919dbf0.JPG)

2019-11-14 06:27 UTC, merged